name: CI (quickscan)

on:
  workflow_dispatch:          # запуск кнопкой
  push:
    branches: [quickscan-mvp] # триггер на эту ветку
  pull_request:
    branches: [quickscan-mvp]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # опционально — быстрый smoke, что requests стоит
      - name: Smoke test
        run: python -c "import requests; print('requests', requests.__version__)"
