services:
  - type: web
    name: metridex-quickscan
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: WEBHOOK_HEADER_SECRET
        sync: false
      - key: BOT_USERNAME
        value: MetridexBot
      - key: REQUEST_TIMEOUT
        value: "5"
      - key: CACHE_TTL_SECONDS
        value: "600"